package com.gearbrother.sheepwolf.rpc.protocol.bussiness {
	import com.gearbrother.sheepwolf.rpc.protocol.*;

	/**
	 * Don't modify manually
	 *
	 * @generated by tool
	 * @create on 2014-05-26 15:10:38
	 */
	public class ApplicationProtocol extends RpcProtocol {
		/**
		 * 服务器同步给的游戏时间，以毫秒为单位
		 */
		static public const SYNTIME:String = "syntime";

		/**
		 * get 服务器同步给的游戏时间，以毫秒为单位
		 */
		public function get syntime():Number {
			return getProperty(SYNTIME);
		}

		/**
		 * set 服务器同步给的游戏时间，以毫秒为单位
		 */
		public function set syntime(newValue:Number):void {
			setProperty(SYNTIME, newValue);
		}

		/**
		 * 
		 */
		static public const $CLASS:String = "$class";

		/**
		 * get 
		 */
		public function get $class():String {
			return getProperty($CLASS);
		}

		/**
		 * set 
		 */
		public function set $class(newValue:String):void {
			setProperty($CLASS, newValue);
		}

		public function ApplicationProtocol(prototype:Object = null) {
			super(prototype);

			if (prototype) {
			}
		}
	}
}
