package com.gearbrother.sheepwolf.rpc.protocol.bussiness {
	import com.gearbrother.sheepwolf.rpc.protocol.*;

	/**
	 * Don't modify manually
	 *
	 * @generated by tool
	 * @create on 2014-05-26 15:10:38
	 */
	public class BattleSignalHpChangeProtocol extends RpcProtocol {
		/**
		 * playerUuid
		 */
		static public const PLAYER_UUID:String = "playerUuid";

		/**
		 * get playerUuid
		 */
		public function get playerUuid():String {
			return getProperty(PLAYER_UUID);
		}

		/**
		 * set playerUuid
		 */
		public function set playerUuid(newValue:String):void {
			setProperty(PLAYER_UUID, newValue);
		}

		/**
		 * hp
		 */
		static public const HP:String = "hp";

		/**
		 * get hp
		 */
		public function get hp():int {
			return getProperty(HP);
		}

		/**
		 * set hp
		 */
		public function set hp(newValue:int):void {
			setProperty(HP, newValue);
		}

		/**
		 * 
		 */
		static public const $CLASS:String = "$class";

		/**
		 * get 
		 */
		public function get $class():String {
			return getProperty($CLASS);
		}

		/**
		 * set 
		 */
		public function set $class(newValue:String):void {
			setProperty($CLASS, newValue);
		}

		public function BattleSignalHpChangeProtocol(prototype:Object = null) {
			super(prototype);

			if (prototype) {
			}
		}
	}
}
