package com.gearbrother.sheepwolf.rpc.protocol.bussiness {
	import com.gearbrother.sheepwolf.rpc.protocol.*;

	/**
	 * Don't modify manually
	 *
	 * @generated by tool
	 * @create on 2014-05-26 15:10:38
	 */
	public class BattleSignalKeyboardDownProtocol extends RpcProtocol {
		/**
		 * playerUuid
		 */
		static public const PLAYER_UUID:String = "playerUuid";

		/**
		 * get playerUuid
		 */
		public function get playerUuid():String {
			return getProperty(PLAYER_UUID);
		}

		/**
		 * set playerUuid
		 */
		public function set playerUuid(newValue:String):void {
			setProperty(PLAYER_UUID, newValue);
		}

		/**
		 * x
		 */
		static public const X:String = "x";

		/**
		 * get x
		 */
		public function get x():Number {
			return getProperty(X);
		}

		/**
		 * set x
		 */
		public function set x(newValue:Number):void {
			setProperty(X, newValue);
		}

		/**
		 * y
		 */
		static public const Y:String = "y";

		/**
		 * get y
		 */
		public function get y():Number {
			return getProperty(Y);
		}

		/**
		 * set y
		 */
		public function set y(newValue:Number):void {
			setProperty(Y, newValue);
		}

		/**
		 * keyCode
		 */
		static public const KEY_CODE:String = "keyCode";

		/**
		 * get keyCode
		 */
		public function get keyCode():int {
			return getProperty(KEY_CODE);
		}

		/**
		 * set keyCode
		 */
		public function set keyCode(newValue:int):void {
			setProperty(KEY_CODE, newValue);
		}

		/**
		 * 开始时间
		 */
		static public const TIME:String = "time";

		/**
		 * get 开始时间
		 */
		public function get time():Number {
			return getProperty(TIME);
		}

		/**
		 * set 开始时间
		 */
		public function set time(newValue:Number):void {
			setProperty(TIME, newValue);
		}

		/**
		 * 
		 */
		static public const $CLASS:String = "$class";

		/**
		 * get 
		 */
		public function get $class():String {
			return getProperty($CLASS);
		}

		/**
		 * set 
		 */
		public function set $class(newValue:String):void {
			setProperty($CLASS, newValue);
		}

		public function BattleSignalKeyboardDownProtocol(prototype:Object = null) {
			super(prototype);

			if (prototype) {
			}
		}
	}
}
