package com.gearbrother.sheepwolf.rpc.protocol.bussiness {
	import com.gearbrother.sheepwolf.rpc.protocol.*;

	/**
	 * Don't modify manually
	 *
	 * @generated by tool
	 * @create on 2014-05-26 15:10:38
	 */
	public class BattleSignalMoveProtocol extends RpcProtocol {
		/**
		 * playerUuid
		 */
		static public const PLAYER_UUID:String = "playerUuid";

		/**
		 * get playerUuid
		 */
		public function get playerUuid():String {
			return getProperty(PLAYER_UUID);
		}

		/**
		 * set playerUuid
		 */
		public function set playerUuid(newValue:String):void {
			setProperty(PLAYER_UUID, newValue);
		}

		/**
		 * x
		 */
		static public const X:String = "x";

		/**
		 * get x
		 */
		public function get x():Number {
			return getProperty(X);
		}

		/**
		 * set x
		 */
		public function set x(newValue:Number):void {
			setProperty(X, newValue);
		}

		/**
		 * y
		 */
		static public const Y:String = "y";

		/**
		 * get y
		 */
		public function get y():Number {
			return getProperty(Y);
		}

		/**
		 * set y
		 */
		public function set y(newValue:Number):void {
			setProperty(Y, newValue);
		}

		/**
		 * 命令执行时服务器时间
		 */
		static public const START_TIME:String = "startTime";

		/**
		 * get 命令执行时服务器时间
		 */
		public function get startTime():Number {
			return getProperty(START_TIME);
		}

		/**
		 * set 命令执行时服务器时间
		 */
		public function set startTime(newValue:Number):void {
			setProperty(START_TIME, newValue);
		}

		/**
		 * 方向
		 */
		static public const DIRECTION:String = "direction";

		/**
		 * get 方向
		 */
		public function get direction():int {
			return getProperty(DIRECTION);
		}

		/**
		 * set 方向
		 */
		public function set direction(newValue:int):void {
			setProperty(DIRECTION, newValue);
		}

		public function BattleSignalMoveProtocol(prototype:Object = null) {
			super(prototype);

			if (prototype) {
			}
		}
	}
}
