package com.gearbrother.sheepwolf.rpc.protocol.bussiness {
	import com.gearbrother.sheepwolf.rpc.protocol.*;

	/**
	 * Don't modify manually
	 *
	 * @generated by tool
	 * @create on 2014-05-26 15:10:38
	 */
	public class BattleSignalUnreadyProtocol extends RpcProtocol {
		/**
		 * 准备玩家
		 */
		static public const UNREADY_USER_UUID:String = "unreadyUserUuid";

		/**
		 * get 准备玩家
		 */
		public function get unreadyUserUuid():String {
			return getProperty(UNREADY_USER_UUID);
		}

		/**
		 * set 准备玩家
		 */
		public function set unreadyUserUuid(newValue:String):void {
			setProperty(UNREADY_USER_UUID, newValue);
		}

		/**
		 * 
		 */
		static public const $CLASS:String = "$class";

		/**
		 * get 
		 */
		public function get $class():String {
			return getProperty($CLASS);
		}

		/**
		 * set 
		 */
		public function set $class(newValue:String):void {
			setProperty($CLASS, newValue);
		}

		public function BattleSignalUnreadyProtocol(prototype:Object = null) {
			super(prototype);

			if (prototype) {
			}
		}
	}
}
