package com.gearbrother.sheepwolf.rpc.protocol.bussiness {
	import com.gearbrother.sheepwolf.rpc.protocol.*;

	/**
	 * Don't modify manually
	 *
	 * @generated by tool
	 * @create on 2014-05-26 15:10:38
	 */
	public class BattleSignalBeginProtocol extends RpcProtocol {
		/**
		 * 战斗
		 */
		static public const BATTLE:String = "battle";

		/**
		 * get 战斗
		 */
		public function get battle():BattleProtocol {
			return getProperty(BATTLE);
		}

		/**
		 * set 战斗
		 */
		public function set battle(newValue:BattleProtocol):void {
			setProperty(BATTLE, newValue);
		}

		/**
		 * 
		 */
		static public const $CLASS:String = "$class";

		/**
		 * get 
		 */
		public function get $class():String {
			return getProperty($CLASS);
		}

		/**
		 * set 
		 */
		public function set $class(newValue:String):void {
			setProperty($CLASS, newValue);
		}

		public function BattleSignalBeginProtocol(prototype:Object = null) {
			super(prototype);

			if (prototype) {
				if (prototype[BATTLE])
					prototype[BATTLE] = prototype2Protocol(prototype[BATTLE]);
			}
		}
	}
}
