package com.gearbrother.sheepwolf.rpc.protocol.bussiness {
	import com.gearbrother.sheepwolf.rpc.protocol.*;

	/**
	 * Don't modify manually
	 *
	 * @generated by tool
	 * @create on 2014-05-26 15:10:38
	 */
	public class BattleSignalAttackProtocol extends RpcProtocol {
		/**
		 * 开火者唯一ID
		 */
		static public const TEAM_UUID:String = "teamUuid";

		/**
		 * get 开火者唯一ID
		 */
		public function get teamUuid():String {
			return getProperty(TEAM_UUID);
		}

		/**
		 * set 开火者唯一ID
		 */
		public function set teamUuid(newValue:String):void {
			setProperty(TEAM_UUID, newValue);
		}

		/**
		 * x
		 */
		static public const X:String = "x";

		/**
		 * get x
		 */
		public function get x():int {
			return getProperty(X);
		}

		/**
		 * set x
		 */
		public function set x(newValue:int):void {
			setProperty(X, newValue);
		}

		/**
		 * y
		 */
		static public const Y:String = "y";

		/**
		 * get y
		 */
		public function get y():int {
			return getProperty(Y);
		}

		/**
		 * set y
		 */
		public function set y(newValue:int):void {
			setProperty(Y, newValue);
		}

		/**
		 * 受击方Uuid
		 */
		static public const TARGET_TEAM_UUID:String = "targetTeamUuid";

		/**
		 * get 受击方Uuid
		 */
		public function get targetTeamUuid():String {
			return getProperty(TARGET_TEAM_UUID);
		}

		/**
		 * set 受击方Uuid
		 */
		public function set targetTeamUuid(newValue:String):void {
			setProperty(TARGET_TEAM_UUID, newValue);
		}

		/**
		 * 开始时间
		 */
		static public const TIME:String = "time";

		/**
		 * get 开始时间
		 */
		public function get time():Number {
			return getProperty(TIME);
		}

		/**
		 * set 开始时间
		 */
		public function set time(newValue:Number):void {
			setProperty(TIME, newValue);
		}

		/**
		 * 
		 */
		static public const $CLASS:String = "$class";

		/**
		 * get 
		 */
		public function get $class():String {
			return getProperty($CLASS);
		}

		/**
		 * set 
		 */
		public function set $class(newValue:String):void {
			setProperty($CLASS, newValue);
		}

		public function BattleSignalAttackProtocol(prototype:Object = null) {
			super(prototype);

			if (prototype) {
			}
		}
	}
}
