package com.gearbrother.sheepwolf.rpc.protocol.bussiness {
	import com.gearbrother.sheepwolf.rpc.protocol.*;

	/**
	 * Don't modify manually
	 *
	 * @generated by tool
	 * @create on 2014-05-26 15:10:38
	 */
	public class BattleSignalReadyProtocol extends RpcProtocol {
		/**
		 * 准备玩家
		 */
		static public const READY_USER:String = "readyUser";

		/**
		 * get 准备玩家
		 */
		public function get readyUser():BattleUserProtocol {
			return getProperty(READY_USER);
		}

		/**
		 * set 准备玩家
		 */
		public function set readyUser(newValue:BattleUserProtocol):void {
			setProperty(READY_USER, newValue);
		}

		/**
		 * 
		 */
		static public const $CLASS:String = "$class";

		/**
		 * get 
		 */
		public function get $class():String {
			return getProperty($CLASS);
		}

		/**
		 * set 
		 */
		public function set $class(newValue:String):void {
			setProperty($CLASS, newValue);
		}

		public function BattleSignalReadyProtocol(prototype:Object = null) {
			super(prototype);

			if (prototype) {
				if (prototype[READY_USER])
					prototype[READY_USER] = prototype2Protocol(prototype[READY_USER]);
			}
		}
	}
}
