package com.gearbrother.sheepwolf.rpc.protocol.bussiness {
	import com.gearbrother.sheepwolf.rpc.protocol.*;

	/**
	 * Don't modify manually
	 *
	 * @generated by tool
	 * @create on 2014-05-26 15:10:38
	 */
	public class BattleSignalTouchProtocol extends RpcProtocol {
		/**
		 * 触碰的ids
		 */
		static public const COLLISION_IDS:String = "collisionIds";

		/**
		 * get 触碰的ids
		 */
		public function get collisionIds():Array {
			return getProperty(COLLISION_IDS);
		}

		/**
		 * set 触碰的ids
		 */
		public function set collisionIds(newValue:Array):void {
			setProperty(COLLISION_IDS, newValue);
		}

		/**
		 * 
		 */
		static public const $CLASS:String = "$class";

		/**
		 * get 
		 */
		public function get $class():String {
			return getProperty($CLASS);
		}

		/**
		 * set 
		 */
		public function set $class(newValue:String):void {
			setProperty($CLASS, newValue);
		}

		public function BattleSignalTouchProtocol(prototype:Object = null) {
			super(prototype);

			if (prototype) {
			}
		}
	}
}
