package com.gearbrother.sheepwolf.rpc.protocol.bussiness {
	import com.gearbrother.sheepwolf.rpc.protocol.*;

	/**
	 * Don't modify manually
	 *
	 * @generated by tool
	 * @create on 2014-05-26 15:10:38
	 */
	public class BattleSignalMethodDoProtocol extends RpcProtocol {
		/**
		 * 方法名
		 */
		static public const METHOD:String = "method";

		/**
		 * get 方法名
		 */
		public function get method():String {
			return getProperty(METHOD);
		}

		/**
		 * set 方法名
		 */
		public function set method(newValue:String):void {
			setProperty(METHOD, newValue);
		}

		/**
		 * 方法参数
		 */
		static public const ARGUS_JSON:String = "argusJson";

		/**
		 * get 方法参数
		 */
		public function get argusJson():String {
			return getProperty(ARGUS_JSON);
		}

		/**
		 * set 方法参数
		 */
		public function set argusJson(newValue:String):void {
			setProperty(ARGUS_JSON, newValue);
		}

		/**
		 * 
		 */
		static public const $CLASS:String = "$class";

		/**
		 * get 
		 */
		public function get $class():String {
			return getProperty($CLASS);
		}

		/**
		 * set 
		 */
		public function set $class(newValue:String):void {
			setProperty($CLASS, newValue);
		}

		public function BattleSignalMethodDoProtocol(prototype:Object = null) {
			super(prototype);

			if (prototype) {
			}
		}
	}
}
