package com.gearbrother.sheepwolf.rpc.protocol.bussiness {
	import com.gearbrother.sheepwolf.rpc.protocol.*;

	/**
	 * Don't modify manually
	 *
	 * @generated by tool
	 * @create on 2014-05-26 15:10:38
	 */
	public class BattleWalkProtocol extends RpcProtocol {
		/**
		 * 玩家uuid
		 */
		static public const USER_UUID:String = "userUuid";

		/**
		 * get 玩家uuid
		 */
		public function get userUuid():String {
			return getProperty(USER_UUID);
		}

		/**
		 * set 玩家uuid
		 */
		public function set userUuid(newValue:String):void {
			setProperty(USER_UUID, newValue);
		}

		/**
		 * 开始位置
		 */
		static public const START_POS:String = "startPos";

		/**
		 * get 开始位置
		 */
		public function get startPos():DPointProtocol {
			return getProperty(START_POS);
		}

		/**
		 * set 开始位置
		 */
		public function set startPos(newValue:DPointProtocol):void {
			setProperty(START_POS, newValue);
		}

		/**
		 * 方向
		 */
		static public const DIRECTION:String = "direction";

		/**
		 * get 方向
		 */
		public function get direction():int {
			return getProperty(DIRECTION);
		}

		/**
		 * set 方向
		 */
		public function set direction(newValue:int):void {
			setProperty(DIRECTION, newValue);
		}

		/**
		 * 开始时间
		 */
		static public const START_TIME:String = "startTime";

		/**
		 * get 开始时间
		 */
		public function get startTime():Number {
			return getProperty(START_TIME);
		}

		/**
		 * set 开始时间
		 */
		public function set startTime(newValue:Number):void {
			setProperty(START_TIME, newValue);
		}

		/**
		 * 结束时间
		 */
		static public const END_TIME:String = "endTime";

		/**
		 * get 结束时间
		 */
		public function get endTime():Number {
			return getProperty(END_TIME);
		}

		/**
		 * set 结束时间
		 */
		public function set endTime(newValue:Number):void {
			setProperty(END_TIME, newValue);
		}

		/**
		 * 
		 */
		static public const $CLASS:String = "$class";

		/**
		 * get 
		 */
		public function get $class():String {
			return getProperty($CLASS);
		}

		/**
		 * set 
		 */
		public function set $class(newValue:String):void {
			setProperty($CLASS, newValue);
		}

		public function BattleWalkProtocol(prototype:Object = null) {
			super(prototype);

			if (prototype) {
				if (prototype[START_POS])
					prototype[START_POS] = prototype2Protocol(prototype[START_POS]);
			}
		}
	}
}
