package com.gearbrother.sheepwolf.rpc.protocol.bussiness {
	import com.gearbrother.sheepwolf.rpc.protocol.*;

	/**
	 * Don't modify manually
	 *
	 * @generated by tool
	 * @create on 2014-05-26 15:10:38
	 */
	public class BattleSignalToolProtocol extends RpcProtocol {
		/**
		 * playerUuid
		 */
		static public const PLAYER_UUID:String = "playerUuid";

		/**
		 * get playerUuid
		 */
		public function get playerUuid():String {
			return getProperty(PLAYER_UUID);
		}

		/**
		 * set playerUuid
		 */
		public function set playerUuid(newValue:String):void {
			setProperty(PLAYER_UUID, newValue);
		}

		/**
		 * 道具id
		 */
		static public const TOOL_CONF_ID:String = "toolConfId";

		/**
		 * get 道具id
		 */
		public function get toolConfId():String {
			return getProperty(TOOL_CONF_ID);
		}

		/**
		 * set 道具id
		 */
		public function set toolConfId(newValue:String):void {
			setProperty(TOOL_CONF_ID, newValue);
		}

		/**
		 * 服务器时间
		 */
		static public const TIME:String = "time";

		/**
		 * get 服务器时间
		 */
		public function get time():Number {
			return getProperty(TIME);
		}

		/**
		 * set 服务器时间
		 */
		public function set time(newValue:Number):void {
			setProperty(TIME, newValue);
		}

		/**
		 * x
		 */
		static public const X:String = "x";

		/**
		 * get x
		 */
		public function get x():Number {
			return getProperty(X);
		}

		/**
		 * set x
		 */
		public function set x(newValue:Number):void {
			setProperty(X, newValue);
		}

		/**
		 * y
		 */
		static public const Y:String = "y";

		/**
		 * get y
		 */
		public function get y():Number {
			return getProperty(Y);
		}

		/**
		 * set y
		 */
		public function set y(newValue:Number):void {
			setProperty(Y, newValue);
		}

		/**
		 * 玩家方向
		 */
		static public const DIRECT:String = "direct";

		/**
		 * get 玩家方向
		 */
		public function get direct():int {
			return getProperty(DIRECT);
		}

		/**
		 * set 玩家方向
		 */
		public function set direct(newValue:int):void {
			setProperty(DIRECT, newValue);
		}

		/**
		 * 
		 */
		static public const $CLASS:String = "$class";

		/**
		 * get 
		 */
		public function get $class():String {
			return getProperty($CLASS);
		}

		/**
		 * set 
		 */
		public function set $class(newValue:String):void {
			setProperty($CLASS, newValue);
		}

		public function BattleSignalToolProtocol(prototype:Object = null) {
			super(prototype);

			if (prototype) {
			}
		}
	}
}
