package com.gearbrother.sheepwolf.rpc.protocol.bussiness {
	import com.gearbrother.sheepwolf.rpc.protocol.*;

	/**
	 * Don't modify manually
	 *
	 * @generated by tool
	 * @create on 2014-05-26 15:10:38
	 */
	public class HallProtocol extends RpcProtocol {
		/**
		 * 大厅唯一ID
		 */
		static public const UUID:String = "uuid";

		/**
		 * get 大厅唯一ID
		 */
		public function get uuid():String {
			return getProperty(UUID);
		}

		/**
		 * set 大厅唯一ID
		 */
		public function set uuid(newValue:String):void {
			setProperty(UUID, newValue);
		}

		/**
		 * 等候的房间
		 */
		static public const ROOMS:String = "rooms";

		/**
		 * get 等候的房间
		 */
		public function get rooms():Object {
			return getProperty(ROOMS);
		}

		/**
		 * set 等候的房间
		 */
		public function set rooms(newValue:Object):void {
			setProperty(ROOMS, newValue);
		}

		/**
		 * 
		 */
		static public const $CLASS:String = "$class";

		/**
		 * get 
		 */
		public function get $class():String {
			return getProperty($CLASS);
		}

		/**
		 * set 
		 */
		public function set $class(newValue:String):void {
			setProperty($CLASS, newValue);
		}

		public function HallProtocol(prototype:Object = null) {
			super(prototype);

			if (prototype) {
				if (prototype[ROOMS])
					prototype[ROOMS] = prototype2Protocol(prototype[ROOMS]);
			}
		}
	}
}
