package com.gearbrother.sheepwolf.rpc.protocol.bussiness {
	import com.gearbrother.sheepwolf.rpc.protocol.*;

	/**
	 * Don't modify manually
	 *
	 * @generated by tool
	 * @create on 2014-05-26 15:10:38
	 */
	public class Protocol {
		static public const Application:String = "com.gearbrother.sheepwolf.pojo.Application";
		static public const BagItem:String = "com.gearbrother.sheepwolf.pojo.BagItem";
		static public const Battle:String = "com.gearbrother.sheepwolf.pojo.Battle";
		static public const BattleSignalAttack:String = "com.gearbrother.sheepwolf.pojo.BattleSignalAttack";
		static public const BattleSignalBegin:String = "com.gearbrother.sheepwolf.pojo.BattleSignalBegin";
		static public const BattleSignalHpChange:String = "com.gearbrother.sheepwolf.pojo.BattleSignalHpChange";
		static public const BattleSignalKeyboardDown:String = "com.gearbrother.sheepwolf.pojo.BattleSignalKeyboardDown";
		static public const BattleSignalKeyboardUp:String = "com.gearbrother.sheepwolf.pojo.BattleSignalKeyboardUp";
		static public const BattleSignalMethodDo:String = "com.gearbrother.sheepwolf.pojo.BattleSignalMethodDo";
		static public const BattleSignalMove:String = "com.gearbrother.sheepwolf.pojo.BattleSignalMove";
		static public const BattleSignalReady:String = "com.gearbrother.sheepwolf.pojo.BattleSignalReady";
		static public const BattleSignalTool:String = "com.gearbrother.sheepwolf.pojo.BattleSignalTool";
		static public const BattleSignalTouch:String = "com.gearbrother.sheepwolf.pojo.BattleSignalTouch";
		static public const BattleSignalUnready:String = "com.gearbrother.sheepwolf.pojo.BattleSignalUnready";
		static public const BattleTool:String = "com.gearbrother.sheepwolf.pojo.BattleTool";
		static public const BattleUser:String = "com.gearbrother.sheepwolf.pojo.BattleUser";
		static public const BattleWalk:String = "com.gearbrother.sheepwolf.pojo.BattleWalk";
		static public const DPoint:String = "com.gearbrother.sheepwolf.pojo.DPoint";
		static public const Explorer:String = "com.gearbrother.sheepwolf.pojo.Explorer";
		static public const Hall:String = "com.gearbrother.sheepwolf.pojo.Hall";
		static public const Room:String = "com.gearbrother.sheepwolf.pojo.Room";
		static public const RpcCallResponse:String = "com.gearbrother.sheepwolf.pojo.RpcCallResponse";
		static public const User:String = "com.gearbrother.sheepwolf.pojo.User";
		static public const protocols:Object = new Object();
		{
			protocols[Application] = ApplicationProtocol;
			protocols[BagItem] = BagItemProtocol;
			protocols[Battle] = BattleProtocol;
			protocols[BattleSignalAttack] = BattleSignalAttackProtocol;
			protocols[BattleSignalBegin] = BattleSignalBeginProtocol;
			protocols[BattleSignalHpChange] = BattleSignalHpChangeProtocol;
			protocols[BattleSignalKeyboardDown] = BattleSignalKeyboardDownProtocol;
			protocols[BattleSignalKeyboardUp] = BattleSignalKeyboardUpProtocol;
			protocols[BattleSignalMethodDo] = BattleSignalMethodDoProtocol;
			protocols[BattleSignalMove] = BattleSignalMoveProtocol;
			protocols[BattleSignalReady] = BattleSignalReadyProtocol;
			protocols[BattleSignalTool] = BattleSignalToolProtocol;
			protocols[BattleSignalTouch] = BattleSignalTouchProtocol;
			protocols[BattleSignalUnready] = BattleSignalUnreadyProtocol;
			protocols[BattleTool] = BattleToolProtocol;
			protocols[BattleUser] = BattleUserProtocol;
			protocols[BattleWalk] = BattleWalkProtocol;
			protocols[DPoint] = DPointProtocol;
			protocols[Explorer] = ExplorerProtocol;
			protocols[Hall] = HallProtocol;
			protocols[Room] = RoomProtocol;
			protocols[RpcCallResponse] = RpcCallResponseProtocol;
			protocols[User] = UserProtocol;
		}
	}
}
