package com.gearbrother.sheepwolf.rpc.protocol.bussiness {
	import com.gearbrother.sheepwolf.rpc.protocol.*;

	/**
	 * Don't modify manually
	 *
	 * @generated by tool
	 * @create on 2014-05-26 15:10:38
	 */
	public class RoomProtocol extends RpcProtocol {
		/**
		 * 唯一id
		 */
		static public const UUID:String = "uuid";

		/**
		 * get 唯一id
		 */
		public function get uuid():String {
			return getProperty(UUID);
		}

		/**
		 * set 唯一id
		 */
		public function set uuid(newValue:String):void {
			setProperty(UUID, newValue);
		}

		/**
		 * 房间名字
		 */
		static public const NAME:String = "name";

		/**
		 * get 房间名字
		 */
		public function get name():String {
			return getProperty(NAME);
		}

		/**
		 * set 房间名字
		 */
		public function set name(newValue:String):void {
			setProperty(NAME, newValue);
		}

		/**
		 * 战斗
		 */
		static public const BATTLE:String = "battle";

		/**
		 * get 战斗
		 */
		public function get battle():BattleProtocol {
			return getProperty(BATTLE);
		}

		/**
		 * set 战斗
		 */
		public function set battle(newValue:BattleProtocol):void {
			setProperty(BATTLE, newValue);
		}

		/**
		 * 
		 */
		static public const $CLASS:String = "$class";

		/**
		 * get 
		 */
		public function get $class():String {
			return getProperty($CLASS);
		}

		/**
		 * set 
		 */
		public function set $class(newValue:String):void {
			setProperty($CLASS, newValue);
		}

		public function RoomProtocol(prototype:Object = null) {
			super(prototype);

			if (prototype) {
				if (prototype[BATTLE])
					prototype[BATTLE] = prototype2Protocol(prototype[BATTLE]);
			}
		}
	}
}
