package com.gearbrother.sheepwolf.rpc.protocol.bussiness {
	import com.gearbrother.sheepwolf.rpc.protocol.*;

	/**
	 * Don't modify manually
	 *
	 * @generated by tool
	 * @create on 2014-05-26 15:10:38
	 */
	public class UserProtocol extends RpcProtocol {
		/**
		 * 用户身份唯一id
		 */
		static public const UUID:String = "uuid";

		/**
		 * get 用户身份唯一id
		 */
		public function get uuid():String {
			return getProperty(UUID);
		}

		/**
		 * set 用户身份唯一id
		 */
		public function set uuid(newValue:String):void {
			setProperty(UUID, newValue);
		}

		/**
		 * 玩家名称
		 */
		static public const NAME:String = "name";

		/**
		 * get 玩家名称
		 */
		public function get name():String {
			return getProperty(NAME);
		}

		/**
		 * set 玩家名称
		 */
		public function set name(newValue:String):void {
			setProperty(NAME, newValue);
		}

		/**
		 * 拥有金币
		 */
		static public const GOLD:String = "gold";

		/**
		 * get 拥有金币
		 */
		public function get gold():int {
			return getProperty(GOLD);
		}

		/**
		 * set 拥有金币
		 */
		public function set gold(newValue:int):void {
			setProperty(GOLD, newValue);
		}

		/**
		 * 拥有银币
		 */
		static public const SILVER:String = "silver";

		/**
		 * get 拥有银币
		 */
		public function get silver():int {
			return getProperty(SILVER);
		}

		/**
		 * set 拥有银币
		 */
		public function set silver(newValue:int):void {
			setProperty(SILVER, newValue);
		}

		/**
		 * 威望，通过战斗获得，用于升级士兵
		 */
		static public const PRESTIGE:String = "prestige";

		/**
		 * get 威望，通过战斗获得，用于升级士兵
		 */
		public function get prestige():int {
			return getProperty(PRESTIGE);
		}

		/**
		 * set 威望，通过战斗获得，用于升级士兵
		 */
		public function set prestige(newValue:int):void {
			setProperty(PRESTIGE, newValue);
		}

		/**
		 * 模型
		 */
		static public const AVATARS:String = "avatars";

		/**
		 * get 模型
		 */
		public function get avatars():Object {
			return getProperty(AVATARS);
		}

		/**
		 * set 模型
		 */
		public function set avatars(newValue:Object):void {
			setProperty(AVATARS, newValue);
		}

		/**
		 * 背包
		 */
		static public const BAG_ITEMS:String = "bagItems";

		/**
		 * get 背包
		 */
		public function get bagItems():Object {
			return getProperty(BAG_ITEMS);
		}

		/**
		 * set 背包
		 */
		public function set bagItems(newValue:Object):void {
			setProperty(BAG_ITEMS, newValue);
		}

		/**
		 * 
		 */
		static public const $CLASS:String = "$class";

		/**
		 * get 
		 */
		public function get $class():String {
			return getProperty($CLASS);
		}

		/**
		 * set 
		 */
		public function set $class(newValue:String):void {
			setProperty($CLASS, newValue);
		}

		public function UserProtocol(prototype:Object = null) {
			super(prototype);

			if (prototype) {
				if (prototype[AVATARS])
					prototype[AVATARS] = prototype2Protocol(prototype[AVATARS]);
				if (prototype[BAG_ITEMS])
					prototype[BAG_ITEMS] = prototype2Protocol(prototype[BAG_ITEMS]);
			}
		}
	}
}
