package com.gearbrother.sheepwolf.rpc.service.bussiness {
	import com.gearbrother.sheepwolf.rpc.service.*;
	import com.gearbrother.sheepwolf.rpc.channel.RpcSocketChannel;

	/**
	 * Don't modify manually
	 *
	 * @generated by tool
	 * @create on 2014-05-26 15:10:38
	 */
	public class ItemService extends RpcService {
		public function ItemService(channel:RpcSocketChannel) {
			super(channel);
		}

		/**
		 * 移动背包
		 *
		 * @toSpaceSize 购买到空间大小
		 * @successCallback 成功回调
		 * @errorCallback 失败回调
		 */
		public function moveItemInBag(toSpaceSize:String, successCallback:Function = null, errorCallback:Function = null):RpcServiceCall {
			return call("itemService.moveItemInBag", [toSpaceSize], successCallback, errorCallback);
		}
	}
}
