package com.gearbrother.sheepwolf.rpc.service.bussiness {
	import com.gearbrother.sheepwolf.rpc.service.*;
	import com.gearbrother.sheepwolf.rpc.channel.RpcSocketChannel;

	/**
	 * Don't modify manually
	 *
	 * @generated by tool
	 * @create on 2014-05-26 15:10:38
	 */
	public class UserService extends RpcService {
		public function UserService(channel:RpcSocketChannel) {
			super(channel);
		}

		/**
		 * 玩家进入接口，新玩家则注册，老玩家则登陆，返回用户信息
		 *
		 * @userName 玩家名字
		 * @successCallback 成功回调
		 * @errorCallback 失败回调
		 */
		public function login(userName:String, successCallback:Function = null, errorCallback:Function = null):RpcServiceCall {
			return call("userService.login", [userName], successCallback, errorCallback);
		}
	}
}
